//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Turtle.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PATH_FORM                   102
#define IDR_PATHVIEW_TMPL               103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_ROBOTCMD_FORM               105
#define IDR_ROBOTCMDVIEW_TMPL           106
#define IDD_SETUP_FORM                  107
#define IDR_SETUP_TMPL                  108
#define ID_INDICATOR_POS                109
#define IDR_MAINFRAME                   128
#define IDR_MAPTYPE                     129
#define IDD_PEN_WIDTHS                  130
#define IDR_RIGHT_POPUP_MENU            131
#define IDB_BITMAP1                     133
#define IDC_CURSOR1                     135
#define IDD_ROTATE_MAP                  136
#define IDD_ARM_CONTROL_DLG             137
#define IDB_BITMAP2                     138
#define IDB_BITMAP3                     139
#define IDC_TURN_SLIDER                 1000
#define IDC_SPEED_SLIDER                1001
#define IDC_MOTOR_SPEED_STATIC          1002
#define IDC_LIST1                       1003
#define IDC_STATUS_LISTBOX              1003
#define IDC_SLIDER_2_TXT                1003
#define IDC_PAN_SPEED_STATIC            1004
#define IDC_CAMERA_UP                   1005
#define IDC_CAMERA_DOWN                 1006
#define IDC_CAM_PAN_UP_LEFT             1007
#define IDC_CAM_PAN_UP2                 1008
#define IDC_CAM_PAN_UP                  1009
#define IDC_CAM_PAN_UP_RIGHT            1010
#define IDC_CAM_PAN_LEFT                1011
#define IDC_CAM_PAN_UP5                 1012
#define IDC_CAM_PAN_STOP                1013
#define IDC_CAM_PAN_RIGHT               1014
#define IDC_CAM_PAN_DOWN_LEFT           1015
#define IDC_CAM_PAN_DOWN                1016
#define IDC_CAM_PAN_DOWN_RIGHT          1017
#define IDC_MOTOR_TURN_STATIC           1018
#define IDC_STOP_BUTTON                 1019
#define IDC_CENTER_BUTTON               1020
#define IDC_X_AXIS                      1021
#define IDC_STOP_PANIC_STOP             1021
#define IDC_Y_AXIS                      1022
#define IDC_CONTINUE_BUTTON             1022
#define IDC_Z_AXIS                      1023
#define IDC_X_ROT                       1024
#define IDC_Y_ROT                       1025
#define IDC_Z_ROT                       1026
#define IDC_SLIDER0                     1027
#define IDC_SLIDER1                     1028
#define IDC_JOY9                        1029
#define IDC_STATIC2                     1030
#define IDC_BRAKE_BUTTON                1030
#define IDC_STATIC3                     1031
#define IDC_STATIC4                     1032
#define IDC_CAMERA_STOP                 1033
#define IDC_USE_JOYSTICK                1034
#define IDC_CB_HIGH_GEAR                1035
#define IDC_ENABLE_TRACKING             1036
#define IDC_ENABLE_OBJECT_NAV_UPDATE    1036
#define IDC_TCP_NO_DELAY                1037
#define IDC_STR_JOY_BUTTONS             1038
#define IDC_POV                         1039
#define IDC_IP_ADDR1                    1040
#define IDC_SERVO_CW                    1041
#define IDC_IP_ADDR2                    1042
#define IDC_12V_ON                      1043
#define IDC_12V_OFF                     1044
#define IDC_CONNECT_TO_HOST             1045
#define IDC_DISCONNECT_FROM_HOST        1046
#define IDC_SERVO_CENTER                1047
#define IDC_CONNECT_TO_LOCAL_HOST       1048
#define IDC_CONNECT_TO_IP_CAMERA        1049
#define IDC_SERVO_CCW                   1050
#define IDC_CAMERA_PWR_OFF              1051
#define IDC_STATUS                      1052
#define IDC_CONNECT_SPEED               1053
#define IDC_PAN_SPEED                   1054
#define IDC_CAMERA_PWR_ON               1055
#define IDC_GET_VERSION                 1056
#define IDC_POWER_DISPLAY               1057
#define IDC_STAT_POWER                  1058
#define IDC_STAT_CURRENT_DRAW           1058
#define IDC_RESET_WATCHDOG              1059
#define IDC_EZUSB_DEBUG_DISPLAY         1060
#define IDC_DEBUG_DISPLAY               1061
#define IDC_STAT_DEBUG                  1062
#define IDC_PAN_CENTER                  1063
#define IDC_ZOOM_IN                     1064
#define IDC_ZOOM_STOP                   1065
#define IDC_ZOOM_OUT                    1066
#define IDC_TEST_SERVO_SPIN             1067
#define IDC_CAMERA_ON                   1068
#define IDC_CAMERA_OFF                  1069
#define IDC_PLAY_MUSIC                  1070
#define IDC_STOP_ZC_SVC                 1071
#define IDC_START_ZC_SVC                1072
#define IDC_RADAR_DISPLAY               1073
#define IDC_RC2_DISPLAY                 1073
#define IDC_WATCHDOG                    1074
#define IDC_STAT_WATCHDOG               1075
#define IDC_VERSION                     1076
#define IDC_STAT_VERSION                1077
#define IDC_RC1_DISPLAY                 1077
#define IDC_PIC_STATUS                  1077
#define IDC_RADAR_SCAN                  1078
#define IDC_RC1_STATUS                  1078
#define IDC_DYNA_STATUS                 1079
#define IDC_KERR_STATUS                 1080
#define IDC_SERVO_NUM                   1081
#define IDC_RX64_STATUS                 1082
#define IDC_MOTOR_STATUS                1082
#define IDC_ARM_L_STATUS                1083
#define IDC_ARM_R_STATUS                1084
#define IDC_HEAD_STATUS                 1085
#define IDC_STAT_BATTERY                1086
#define IDC_SONG2                       1087
#define IDC_STAT_BATTERY_VOLTS          1087
#define IDC_KINECT_STATUS               1088
#define IDC_IR_SCAN                     1089
#define IDC_STAT_BASE_DOCKED            1089
#define IDC_EZUSB_BUMPER_DISPLAY        1090
#define IDC_STAT_BATTERY_VOLTS3         1090
#define IDC_STAT_PLUG_INSERTED          1090
#define IDC_BUMPER_DISPLAY              1091
#define IDC_RADAR_WIN                   1092
#define IDC_AVOID_OBJ_RANGE             1093
#define IDC_LASER_DISPLAY_WIN           1094
#define IDC_PATH_SPEED_ADDER            1095
#define IDC_CAMERA_TRACKING_COLOR_THRESHOLD 1096
#define IDC_BEHAVIOR_MODE               1097
#define IDC_ACTION_MODE                 1098
#define IDC_MOVE_DISTANCE               1099
#define IDC_HEAD_TILT                   1100
#define IDC_TURN_AMOUNT                 1101
#define IDC_IR1_DISPLAY                 1102
#define IDC_HEAD_FORWARD                1102
#define IDC_STAT_IR1                    1103
#define IDC_IR2_DISPLAY                 1104
#define IDC_STAT_IR3                    1104
#define IDC_STAT_US5                    1105
#define IDC_STAT_IR7                    1105
#define IDC_EZUSB_IR2_DISPLAY           1106
#define IDC_STAT_IR2                    1106
#define IDC_STAT_US6                    1107
#define IDC_STAT_IR10                   1107
#define IDC_TEST                        1108
#define IDC_STAT_IR4                    1110
#define IDC_LAST_ERROR_DISPLAY          1111
#define IDC_STAT_LAST_ERROR             1112
#define IDC_OPEN_DEFAULT_PATH           1113
#define IDC_RECALCUALTE_ALL_WAYPOINTS   1113
#define IDC_SAVE_TO_DISK                1113
#define IDC_ARM_MOTION1                 1113
#define IDC_STAT_IR5                    1114
#define IDC_ARM_MOTION2                 1114
#define IDC_CAMERA_TILT_SLIDER          1115
#define IDC_OPEN_UPSTAIRS_MAP           1115
#define IDC_ARM_MOTION3                 1115
#define IDC_SERVO_VALUE                 1116
#define IDC_OPEN_DOWNSTAIRS_MAP         1116
#define IDC_ARM_MOTION4                 1116
#define IDC_CAMERA_TILT_STATIC          1117
#define IDC_OPEN_BLANK_MAP              1117
#define IDC_ARM_MOTION5                 1117
#define IDC_CAMERA_WIN                  1118
#define IDC_ARM_MOTION6                 1118
#define IDC_STAT_COMPASS                1119
#define IDC_ARM_MOTION7                 1119
#define IDC_COMPASS_DIR                 1120
#define IDC_ARM_MOTION8                 1120
#define IDC_STAT_IR0                    1121
#define IDC_ARM_MOTION9                 1121
#define IDC_BEHAVIOR_MODE_GO            1122
#define IDC_STAT_IR_BUMPER_LOW_FRONT_LEFT 1122
#define IDC_ARM_MOTION10                1122
#define IDC_STAT_IR11                   1122
#define IDC_STAT_COMPASS_ERROR          1123
#define IDC_ARM_MOTION11                1123
#define IDC_STAT_MOTOR_L                1124
#define IDC_STAT_TACH                   1124
#define IDC_ARM_MOTION12                1124
#define IDC_STAT_MOTOR_R                1125
#define IDC_STAT_ODOMETER               1125
#define IDC_ARM_MOTION13                1125
#define IDC_BATTERY_WARNING_TEXT        1126
#define IDC_ARM_MOTION14                1126
#define IDC_MOVE_DISTANCE_FORWARD       1127
#define IDC_ARM_MOTION15                1127
#define IDC_TURN_DISTANCE_LEFT          1128
#define IDC_ARM_MOTION16                1128
#define IDC_TURN_DISTANCE_RIGHT         1129
#define IDC_ARM_MOTION17                1129
#define IDC_MOVE_DISTANCE_REVERSE       1130
#define IDC_ARM_MOTION18                1130
#define IDC_MOVE_DISTANCE_REVERSE2      1131
#define IDC_STAT_GPS                    1131
#define IDC_ARM_MOTION19                1131
#define IDC_SEGMENT_LISTBOX             1132
#define IDC_STAT_GPS_LONG               1132
#define IDC_WAYPOINT_LISTBOX            1133
#define IDC_STAT_GPS_LAT                1133
#define IDC_SEGMENT_ADD                 1134
#define IDC_STAT_GPS_SATS_IN_VIEW       1134
#define IDC_SEGMENT_INSERT              1135
#define IDC_STAT_US2                    1135
#define IDC_SEGMENT_UPDATE              1136
#define IDC_STAT_US1                    1136
#define IDC_SEGMENT_REMOVE              1137
#define IDC_STAT_US0                    1137
#define IDC_SEGMENT_REMOVE_ALL          1138
#define IDC_STAT_US3                    1138
#define IDC_STAT_IR8                    1138
#define IDC_WAYPOINT_ADD                1139
#define IDC_STAT_US4                    1139
#define IDC_STAT_IR9                    1139
#define IDC_WAYPOINT_INSERT             1140
#define IDC_STAT_IR6                    1140
#define IDC_STAT_IR_BUMPER_LOW_FRONT_RIGHT 1140
#define IDC_WAYPOINT_UPDATE             1141
#define IDC_STAT_IR_AD_VERT_FRONT_RIGHT 1141
#define IDC_WAYPOINT_REMOVE             1142
#define IDC_STAT_IR_AD_VERT_FRONT_LEFT  1142
#define IDC_WAYPOINT_REMOVE_ALL         1143
#define IDC_STAT_CLIFF_RIGHT            1143
#define IDC_SEGMENT_BEHAVIOR            1144
#define IDC_STAT_CLIFF_LEFT             1144
#define IDC_WAYPOINT_LANDMARK_TYPE1     1145
#define IDC_STAT_BMPR_RIGHT             1145
#define IDC_SEGMENT_PARAMETER           1146
#define IDC_STAT_GPS_LONG2              1146
#define IDC_STAT_BMPR_LEFT              1146
#define IDC_EDIT_WAYPOINT_X             1147
#define IDC_STAT_GPS_LAT2               1147
#define IDC_STAT_BMPR_FRONT             1147
#define IDC_WAYPOINT_X_FEET             1148
#define IDC_STAT_BMPR_REAR              1148
#define IDC_EDIT_WAYPOINT_Y             1149
#define IDC_STAT_GPS_SATS_IN_VIEW2      1149
#define IDC_STAT_IR_BUMPER_LOW_REAR_RIGHT 1149
#define IDC_LAUNCH_MAP_DIALOG           1150
#define IDC_ANCHOR_POINT_X              1150
#define IDC_STAT_IR_BUMPER_LOW_REAR_LEFT 1150
#define IDC_WAYPOINT_X_INCHES           1151
#define IDC_STAT_PIR_RIGHT              1151
#define IDC_SEGMENT_NAME                1152
#define IDC_STAT_PIR_LEFT               1152
#define IDC_SEGMENT_TO_WAYPOINT_ID      1153
#define IDC_IR_BUMPER_ARM_L_FINGER_R    1153
#define IDC_WAYPOINT_NAME               1154
#define IDC_IR_BUMPER_ARM_L_FINGER_L    1154
#define IDC_WAYPOINT_ID                 1155
#define IDC_IR_BUMPER_ARM_R_ELBOW       1155
#define IDC_WAYPOINT_LANDMARK_RANGE1    1156
#define IDC_STAT_FPS                    1156
#define IDC_WAYPOINT_LANDMARK_DIRECTION1 1157
#define IDC_IR_BUMPER_ARM_L_ELBOW       1157
#define IDC_WAYPOINT_LANDMARK_HEIGHT1   1158
#define IDC_IR_HEAD_R                   1158
#define IDC_WAYPOINT_LANDMARK_TYPE2     1159
#define IDC_IR_HEAD_L                   1159
#define IDC_WAYPOINT_LANDMARK_RANGE2    1160
#define IDC_IR_BUMPER_ARM_R_HAND        1160
#define IDC_WAYPOINT_LANDMARK_DIRECTION2 1161
#define IDC_IR_BUMPER_ARM_L_HAND        1161
#define IDC_WAYPOINT_LANDMARK_HEIGHT2   1162
#define IDC_STAT_IR_BUMPER_LOW_REAR_RIGHT2 1162
#define IDC_STAT_KINECT_POSITION        1162
#define IDC_WAYPOINT_LANDMARK_TYPE3     1163
#define IDC_STAT_NEAREST_OBJECT_DISTANCE 1163
#define IDC_WAYPOINT_LANDMARK_RANGE3    1164
#define IDC_WAYPOINT_LANDMARK_DIRECTION3 1165
#define IDC_WAYPOINT_LANDMARK_HEIGHT3   1166
#define IDC_GPS_NEW_WAYPOINT            1167
#define IDC_SET_GPS_ANCHOR_POINT        1167
#define IDC_SEGMENT_MOVE_DOWN           1168
#define IDC_WAYPOINT_Y_FEET             1169
#define IDC_SEGMENT_MOVE_UP             1170
#define IDC_WAYPOINT_MOVE_UP            1171
#define IDC_WAYPOINT_MOVE_DOWN          1172
#define IDC_WAYPOINT_Y_INCHES           1173
#define IDC_SEGMENT_DIRECTION           1174
#define IDC_SEGMENT_FROM_WAYPOINT_ID    1175
#define IDC_SEGMENT_SPEED               1176
#define IDC_SEGMENT_FOLLOW_DISTANCE     1177
#define IDC_SEGMENT_FOLLOW_LEFT         1178
#define IDC_SEGMENT_FOLLOW_RIGHT        1179
#define IDC_SEGMENT_FOLLOW_GAP          1180
#define IDC_SEGMENT_AVOID_DISTANCE      1180
#define IDC_CALCUALTE_NEW_WAYPOINT      1181
#define IDC_SEGMENT_DISTANCE_FEET       1182
#define IDC_SEGMENT_DISTANCE_INCHES     1183
#define IDC_THIN_PEN_WIDTH              1184
#define IDC_ANCHOR_POINT_Y              1184
#define IDC_THICK_PEN_WIDTH             1185
#define IDC_CALCUALTE_NEW_GPS_WAYPOINT  1185
#define IDC_DEFAULT_PEN_WIDTHS          1186
#define IDC_SEGMENT_COMPASS_CORRECTION  1186
#define IDC_OPEN_DEFAULT_MAP            1188
#define IDC_CLIENT_OR_SERVER            1189
#define IDC_STATIC_GPS_BLINK            1192
#define IDC_STAT_GPS2                   1193
#define IDC_STATIC_GPS_BLINK2           1194
#define IDC_PATH_ORIGIN_LONG            1195
#define IDC_PATH_ORIGIN_LAT             1196
#define IDC_EXECUTE_PATH                1198
#define IDC_CAM_UP                      1199
#define IDC_CAM_STOP                    1200
#define IDC_CAM_DOWN                    1201
#define IDC_CAM_RIGHT                   1202
#define IDC_CAM_LEFT                    1203
#define IDC_CAM_UP_RIGHT                1204
#define IDC_CAM_UP_LEFT                 1205
#define IDC_CAM_DOWN_RIGHT              1206
#define IDC_CAM_DOWN_LEFT               1207
#define IDC_CAM_CENTER                  1208
#define IDC_RESET_ODOMETER              1209
#define IDC_CANCEL_PATH                 1210
#define IDC_PAUSE_PATH                  1211
#define IDC_RESUME_PATH                 1212
#define IDC_TEST_BRAKE                  1213
#define IDC_COLOR_TRACK_LOAD_BTN        1215
#define IDC_COLOR_TRACK_CALIBRATE_BTN   1217
#define IDC_COLOR_TRACK_SEARCH_BTN      1218
#define IDC_STAT_COLOR_CAL_RESULT       1219
#define IDC_ENABLE_COLLISION_MODULE     1220
#define IDC_ENABLE_AVOIDANCE_MODULE     1221
#define IDC_ENABLE_GPS_PATH             1222
#define IDC_STAT_KINECT                 1223
#define IDC_CAMERA_MANUAL_COLOR_CALDATA 1226
#define IDC_CAMERA_COLOR_CR             1226
#define IDC_CAMERA_MANUAL_COLOR_CAL_BTN 1227
#define IDC_CAMERA_SCAN_DISTANCE        1228
#define IDC_CAMERA_SCAN_DISTANCE_BTN    1229
#define IDC_COMPASS_CAL_MODE            1230
#define IDC_COMPASS_CAL_POINT           1231
#define IDC_ENABLE_IR0                  1232
#define IDC_CAMERA_COLOR_CB             1232
#define IDC_ENABLE_IR1                  1233
#define IDC_ENABLE_IR2                  1234
#define IDC_ENABLE_IR3                  1235
#define IDC_ENABLE_IR4                  1236
#define IDC_ENABLE_IR5                  1237
#define IDC_ENABLE_US0                  1238
#define IDC_ENABLE_US1                  1239
#define IDC_ENABLE_US2                  1240
#define IDC_BUTTON2                     1241
#define IDC_GPS_OPEN_PORT               1241
#define IDC_RECALC_SEGMENTS             1241
#define IDC_PLAY_SOUND                  1241
#define IDC_TAKE_SNAPSHOT               1241
#define IDC_DRIVE_MODULE_OWNER          1242
#define IDC_OPEN_SERVO_PORT             1242
#define IDC_OPEN_MOTOR_PORT             1243
#define IDC_RECORD_VIDEO                1243
#define IDC_GPS_COM_PORT                1244
#define IDC_SERVO_COM_PORT              1245
#define IDC_MOTOR_COM_PORT              1246
#define IDC_CAMERA_COM_PORT             1247
#define IDC_OPEN_CAMERA_PORT            1248
#define IDC_CAM_PAN_SPEED               1249
#define IDC_CAMERA_POS_ABS_VALUE        1250
#define IDC_CAMERA_POS_ABS_VALUE_X      1250
#define IDC_CAMERA_POS_ABS_BTN          1251
#define IDC_PIC_COM_PORT                1252
#define IDC_OPEN_PIC_PORT               1253
#define IDC_ENABLE_CAMERA_THREAD        1254
#define IDC_ENABLE_CAMERAS              1254
#define IDC_DYNA_RX64_COM_PORT          1254
#define IDC_CAM_TILT_SPEED              1255
#define IDC_CAMERA_POS_ABS_VALUE_Y      1255
#define IDC_CAMERA_ENABLE_TRACKING_FACE 1256
#define IDC_CAMERA_ENABLE_TRACKING_COLORS 1257
#define IDC_CAMERA_ENABLE_TRACKING_CONES 1258
#define IDC_CAMERA_ENABLE_TRACKING_OBJECTS 1259
#define IDC_CAM_ZOOM_LEVEL_ABS          1260
#define IDC_CAMERA_ENABLE_TRACKING_OBJECT_MOTION 1261
#define IDC_CAMERA_ENABLE_SHOW_MOTION_VIEW 1262
#define IDC_CAM_FRAME_SIZE              1263
#define IDC_VIDEO_PROP_BTN              1264
#define IDC_VIDEO_FORMAT_BTN            1265
#define IDC_START_CAMERA                1266
#define IDC_CAMERA_ENABLE_MATCH_OBJECTS 1266
#define IDC_SLIDER_1                    1267
#define IDC_SLIDER_2                    1268
#define IDC_SLIDER_1_TXT                1269
#define IDC_VIDEO_SELECT_CAMERA         1270
#define IDC_OPEN_DYNA_RX64_COM_PORT     1270
#define IDC_OPEN_DYNA_RX64_SERVO_PORT   1270
#define IDC_COLOR_AUTO_CAL_BTN          1271
#define IDC_CAMERA_ENABLE_FACE_IDENTIFY 1272
#define IDC_COLOR_CAL_STATUS            1273
#define IDC_ARM_SPEED                   1274
#define IDC_ARM_SPEED_R                 1274
#define IDC_ENABLE_CAMERA_LIGHTS        1275
#define IDC_ARM_SPEED_L                 1275
#define IDC_ENABLE_LED_EYES             1276
#define IDC_LASER_COM_PORT              1276
#define IDC_ENABLE_AUX_LIGHTS           1277
#define IDC_OPEN_CAMERA_PORT2           1277
#define IDC_OPEN_LASER_PORT             1277
#define IDC_SPEAK                       1278
#define IDC_CAM_DISPLAY_SIZE            1278
#define IDC_LED_EYES_BLINK              1279
#define IDC_KINECT_DISPLAY_SIZE         1279
#define IDC_TEXT_TO_SPEAK               1280
#define IDC_MAP_ROTATION_AMOUNT         1281
#define IDC_ENABLE_CAMERA_1             1282
#define IDC_MAP_SCALE_AMOUNT            1282
#define IDC_ENABLE_CAMERA_2             1283
#define IDC_ENABLE_KINECT               1284
#define IDC_SEND_TO_AI                  1285
#define IDC_CAM_DISPLAY_MODE_ENABLE     1286
#define IDC_CAM_TRACK_MODE_ENABLE       1287
#define IDC_CAM_IR_TRACKING_ENABLE      1288
#define IDC_PERSONAL_SPACE              1289
#define IDC_OPEN_DYNA_SERVO_PORT        1290
#define IDC_DYNA_SERVO_COM_PORT         1291
#define IDC_DYNA_SERVO_TEST_ID          1292
#define IDC_DYNA_SERVO_TEST_POS         1293
#define IDC_DYNA_SERVO_TEST_GO          1294
#define IDC_DYNA_SERVO_REG_NUM          1295
#define IDC_DYNA_SERVO_REG_READ         1296
#define IDC_SERVO_GET_STATUS            1297
#define IDC_DYNA_SERVO_REG_WRITE_BYTE   1298
#define IDC_DYNA_SERVO_REG_WRITE_WORD   1299
#define IDC_DYNA_SERVO_REG_WRITE_VALUE  1300
#define IDC_DYNA_SERVO_NUM_OF_REGISTERS 1301
#define IDC_SPEECH_RECO_SEND_TO_AI      1302
#define IDC_SPEECH_RECO_ENABLE          1303
#define IDC_RIGHT_SHOULDER_ROTATE       1304
#define IDC_RIGHT_ELBOW_ROTATE          1305
#define IDC_RIGHT_ELBOW_BEND            1306
#define IDC_RIGHT_WRIST_ROTATE          1307
#define IDC_RIGHT_GRIP                  1308
#define IDC_SET_RIGHT_ARM_POSITION      1309
#define IDC_READ_RIGHT_ARM_POSITION     1310
#define IDC_CLIFF_SENSORS               1311
#define IDC_R_ARM_POS_PRESET            1312
#define IDC_ENABLE_SERVOS_R             1313
#define IDC_OPEN_KERR_SERVO_PORT        1314
#define IDC_KERR_SERVO_COM_PORT         1315
#define IDC_COPY_RIGHT_ARM_POSITION     1316
#define IDC_LEFT_SHOULDER_ROTATE        1317
#define IDC_RIGHT_SHOULDER_ROTATE_SET   1318
#define IDC_RIGHT_ELBOW_ROTATE_SET      1319
#define IDC_RIGHT_ELBOW_BEND_SET        1320
#define IDC_RIGHT_WRIST_ROTATE_SET      1321
#define IDC_RIGHT_GRIP_SET              1322
#define IDC_ARM_LIMIT_R                 1323
#define IDC_LEFT_ELBOW_ROTATE           1324
#define IDC_LEFT_ELBOW_BEND             1325
#define IDC_DYNA_USB_ENABLE             1326
#define IDC_CAMERA_ENABLE_TRACKING_HAND 1327
#define IDC_CAMERA_ENABLE_STEREO_VISION 1328
#define IDC_RECORD_VIDEO_STOP           1328
#define IDC_ENABLE_VIDEO_PROCESSING     1329
#define IDC_LEFT_WRIST_ROTATE           1330
#define IDC_LEFT_GRIP                   1331
#define IDC_SET_LEFT_ARM_POSITION       1332
#define IDC_READ_LEFT_ARM_POSITION      1333
#define IDC_L_ARM_POS_PRESET            1334
#define IDC_ENABLE_SERVOS_L             1335
#define IDC_LEFT_SHOULDER_ROTATE_SET    1336
#define IDC_LEFT_ELBOW_ROTATE_SET       1337
#define IDC_LEFT_ELBOW_BEND_SET         1338
#define IDC_LEFT_WRIST_ROTATE_SET       1339
#define IDC_LEFT_GRIP_SET               1340
#define IDC_ARM_LIMIT_L                 1341
#define IDC_COPY_LEFT_ARM_POSITION      1342
#define IDC_LAUNCH_APP                  1343
#define IDC_PC_PWR_MODE                 1344
#define IDC_SET_HEAD_POSITION           1344
#define IDC_BOTH_ARM_POS_PRESET         1345
#define IDC_ITUNES_NEXT                 1346
#define IDC_BUTTON4                     1347
#define IDC_CHECK_LOCATION              1347
#define IDC_ITUNES_PRIOR                1348
#define IDC_COMBO2                      1349
#define IDC_LASER_ZOOM                  1349
#define IDC_COPY_HEAD_POSITION          1349
#define IDC_BUTTON3                     1350
#define IDC_REQUEST_LASER_SCANS         1350
#define IDC_ITUNES_FULLSCREEN           1351
#define IDC_CHECK1                      1352
#define IDC_ENABLE_LASER_POWER          1352
#define IDC_LASER_SCAN_ENABLE           1352
#define IDC_EDIT1                       1353
#define IDC_SET_LASER_POSITION          1353
#define IDC_LEFT_SHOULDER_ROTATE_LOAD   1354
#define IDC_FIND_OBJ_AT_XYZ             1355
#define IDC_OBJECT_X                    1356
#define IDC_OBJECT_Y                    1357
#define IDC_OBJECT_Z                    1358
#define IDC_HEAD_PAN_SET                1359
#define IDC_HEAD_PAN_GET                1360
#define IDC_HEAD_TILT_SET               1361
#define IDC_HEAD_TILT_GET               1362
#define IDC_HEAD_SIDETITL_SET           1363
#define IDC_HEAD_SIDETILT_GET           1364
#define IDC_LEFT_ELBOW_ROTATE_LOAD      1365
#define IDC_LEFT_ELBOW_BEND_LOAD        1366
#define IDC_LEFT_WRIST_ROTATE_LOAD      1367
#define IDC_LEFT_GRIP_LOAD              1368
#define IDC_RIGHT_SHOULDER_ROTATE_LOAD  1369
#define IDC_RIGHT_ELBOW_ROTATE_LOAD     1370
#define IDC_RIGHT_ELBOW_BEND_LOAD       1371
#define IDC_RIGHT_WRIST_ROTATE_LOAD     1372
#define IDC_RIGHT_GRIP_LOAD             1373
#define IDC_HEAD_PAN_LOAD               1374
#define IDC_HEAD_TILT_LOAD              1375
#define IDC_HEAD_SIDETILT_LOAD          1376
#define IDC_LASER_SEARCH_FOR_OBJECTS    1377
#define IDC_START_ANGLE                 1378
#define IDC_END_ANGLE                   1379
#define IDC_STEP_ANGLE                  1380
#define IDC_KINECT_UP                   1381
#define IDC_KINECT_DOWN                 1382
#define IDC_KINECT_TILT_GET             1383
#define IDC_KINECT_TILT_SET             1384
#define IDC_CHECK2                      1385
#define IDC_ENABLE_ARMS                 1385
#define IDC_KINECT_PWR                  1385
#define IDC_LOCAL_USER_CB               1385
#define IDC_FLIP_KINECT                 1386
#define IDC_CHECK3                      1387
#define IDC_KINECT_PWR_ENABLE           1387
#define IDC_VIDEO_VIEW                  1388
#define IDC_EDIT_SCRIPT_FILENAME        1389
#define IDC_EDIT_SCRIPT_FILE            1390
#define IDC_RUN_SCRIPT                  1391
#define IDC_EDIT_SCRIPT_TEXT_LINE       1392
#define IDC_ADD_SCRIPT_DELAY            1393
#define IDC_CLOSE_SCRIPT_FILE           1394
#define IDC_FACE_CAPTURE_NAME           1395
#define IDC_CAPTURE_FACE                1396
#define IDC_CASTER_DROP                 1397
#define IDC_LEFT_WHEEL_DROP             1398
#define IDC_RIGHT_WHEEL_DROP            1399
#define IDC_TURTLE_GUI                  1400
#define ID_PEN_THICK_OR_THIN            32771
#define ID_PEN_PENWIDTHS                32772
#define ID_ADD_WAYPONT                  32773
#define ID_RIGHT_MOUSE_MENU             32774
#define ID_SHOW_LOCATION                32775
#define ID_SHOWLOCATION                 32776
#define ID_SEL_CMD_VIEW_BTN             32777
#define ID_SEL_PATH_VIEW_BTN            32778
#define ID_SEL_MAP_VIEW_BTN             32779
#define ID_GPS_ENABLE                   32780
#define ID_SEL_SETUP_VIEW_BTN           32781
#define ID_TYPE_WALLOBJECT              32782
#define ID_TYPE_OBSTACLE                32783
#define ID_TYPE_USERDRAW                32784
#define ID_NAVIGATION_MODE              32785
#define IDC_WAYPOINT_LOCATION           32786
#define ID_ADD_PAGE_ABOVE               32787
#define ID_ADD_PAGE_RIGHT               32788
#define ID_ADD_PAGE_BELOW               32789
#define ID_ADD_PAGE_LEFT                32790
#define ID_SHOW_ROBOT_TRAILS            32791
#define ID_SHOW_GRIDMAP_SQUARES         32792
#define ID_SHOW_SENSOR_READINGS         32793
#define ID_MAP_ZOOM_050                 32794
#define ID_MAP_ZOOM_100                 32795
#define ID_MAP_ZOOM_150                 32796
#define ID_MAP_ZOOM_200                 32797
#define ID_MAP_ZOOM_400                 32798
#define ID_ZOOM_MAP_025                 32799
#define ID_ZOOM_MAP_050                 32800
#define ID_ZOOM_MAP_100                 32801
#define ID_ZOOM_MAP_150                 32802
#define ID_ZOOM_MAP_200                 32803
#define ID_ZOOM_MAP_400                 32804
#define ID_SET_CURRENT_LOCATION         32805
#define ID_EXPORT_TO_FILE               32806
#define ID_IMPORT_TO_FILE               32807
#define ID_IMPORT_FROM_FILE             32808
#define ID_ROTATE_MAP                   32809
#define ID_TYPE_DOOR_OBJECT             32810
#define ID_TYPE_LOW_OBSTACLE            32811
#define ID_TYPE_CLIFF                   32812
#define ID_CLEAR_MOUSE_TRAIL            32814
#define ID_CLEAR_SENSOR_READINGS        32815
#define ID_Q                            32816
#define ID_W                            32817
#define ID_E                            32818
#define ID_S                            32819
#define ID_X                            32820
#define ID_A                            32821
#define ID_D                            32822
#define ID_KEY_PLUS                     32823
#define ID_KEY_MINUS                    32824
#define ID_KEY_ZERO                     32825
#define ID_C                            32826
#define ID_ARM_MOVEMENT                 32827
#define ID_ARM_CONTROL_DLG              32829

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1401
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
